version: "3"
services:
  cache:
    image: redis:alpine
    restart: unless-stopped
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${HOST_PATH_ROOT}/redis/data:/data
  tg_search_bot:
    restart: always
    build: .
    volumes:
      - ${HOST_PATH_ROOT}:${PATH_ROOT}
    network_mode: "host"
    depends_on:
      - cache
