version: "3"

services:
  cache:
    image: redis
    command: bash -c "mkdir -p ${PATH_REDIS} && touch ${PATH_REDIS}/redis.conf && redis-server ${PATH_REDIS}/redis.conf"
    ports:
      - "6379:6379"
    volumes:
      - ${HOST_PATH_ROOT}/redis:${PATH_REDIS}
      - ${HOST_PATH_ROOT}/redis/data:/data
  tg_search_bot:
    build: .
    volumes:
      - ${HOST_PATH_ROOT}:${PATH_ROOT}
    depends_on:
      - cache
    network_mode: "host"